# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90e393fe1126510937c620e59ae5ae9b5add2c494b8d2399b369552223e68b72a59a5c09c1660807a91c36b36d35e781c8f1184296b0115ad271d9dc180735d9

test:
  secret_key_base: 1fdae34d2bb11c9a125bdd82bd75240dc32560586ef7eac65f0bef6387d0a1b7b68e25ed2cdcf91f323da7884d253d9e1f03c3a15941f39d6b2926f138ceeca6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
